In [ ]:
!pip install statsmodels

In [ ]:
# 0. EDA

In [ ]:
########################################

In [17]:
from mixedEffectsResults import full_pipeline

In [18]:
#clases_interes = ['building', 'sky', 'road', 'tree', 'person']
clases_interes = ['ashcan', 'awning', 'bag',
       'bench', 'bicycle', 'box', 'bridge', 'building', 'bus', 'car', 'column',
       'conveyor', 'door', 'fence', 'field', 'floor', 'flowerpot', 'fountain',
       'grass', 'ground', 'handrail', 'hill', 'house', 'lake', 'motorcycle',
       'mountain', 'palm', 'path', 'pedestal', 'person', 'plant', 'pole',
       'poster', 'railing', 'road', 'rock', 'sea', 'sidewalk', 'signboard',
       'sky', 'stair', 'stairs', 'stoplight', 'streetlight', 'table', 'trade',
       'tree', 'truck', 'van', 'wall', 'water', 'windowpane']

result, df_final, df_model, preds = full_pipeline(
    'df_final1.csv',
    'precalculated_saliency_coverage.csv',
    clases_interes
)

print(result.summary())

          Mixed Linear Model Regression Results
==========================================================
Model:              MixedLM Dependent Variable: score
No. Observations:   1500    Method:             REML
No. Groups:         30      Scale:              2.8365
Min. group size:    50      Log-Likelihood:     -3021.4915
Max. group size:    50      Converged:          Yes
Mean group size:    50.0
----------------------------------------------------------
                Coef.  Std.Err.   z    P>|z| [0.025 0.975]
----------------------------------------------------------
Intercept        5.091    0.155 32.767 0.000  4.787  5.396
ashcan_std       0.133    0.044  2.982 0.003  0.045  0.220
awning_std       0.084    0.051  1.670 0.095 -0.015  0.183
bag_std          0.041    0.048  0.867 0.386 -0.052  0.135
bench_std       -0.135    0.047 -2.844 0.004 -0.228 -0.042
bicycle_std     -0.032    0.046 -0.698 0.485 -0.121  0.057
box_std         -0.049    0.045 -1.104 0.269 -0.137  0.038
bridge_std      -0.110    0.053 -2.086 0.037 -0.214 -0.007
building_std     0.180    0.131  1.378 0.168 -0.076  0.436
bus_std          0.143    0.047  3.017 0.003  0.050  0.236
car_std          0.143    0.057  2.522 0.012  0.032  0.254
column_std       0.104    0.045  2.318 0.020  0.016  0.192
door_std         0.222    0.047  4.720 0.000  0.130  0.314
fence_std        0.241    0.067  3.621 0.000  0.111  0.371
field_std       -0.113    0.045 -2.507 0.012 -0.201 -0.025
floor_std        0.036    0.047  0.769 0.442 -0.056  0.128
fountain_std     0.032    0.044  0.717 0.473 -0.055  0.119
grass_std       -0.024    0.053 -0.460 0.646 -0.128  0.079
hill_std         0.079    0.045  1.737 0.082 -0.010  0.167
house_std        0.050    0.049  1.007 0.314 -0.047  0.146
lake_std         0.145    0.050  2.868 0.004  0.046  0.244
mountain_std    -0.166    0.046 -3.574 0.000 -0.257 -0.075
palm_std         0.232    0.056  4.128 0.000  0.122  0.342
path_std         0.154    0.047  3.251 0.001  0.061  0.247
person_std       0.024    0.049  0.496 0.620 -0.071  0.120
plant_std        0.137    0.053  2.609 0.009  0.034  0.240
pole_std        -0.125    0.045 -2.760 0.006 -0.215 -0.036
poster_std      -0.019    0.044 -0.420 0.675 -0.105  0.068
railing_std      0.053    0.046  1.158 0.247 -0.037  0.143
road_std        -0.031    0.081 -0.382 0.703 -0.191  0.128
rock_std         0.043    0.044  0.985 0.324 -0.043  0.130
sea_std         -0.074    0.044 -1.675 0.094 -0.160  0.013
sidewalk_std     0.140    0.066  2.136 0.033  0.012  0.268
signboard_std   -0.065    0.051 -1.294 0.196 -0.164  0.034
sky_std         -0.093    0.065 -1.431 0.152 -0.219  0.034
stairs_std      -0.047    0.045 -1.046 0.296 -0.135  0.041
streetlight_std  0.067    0.045  1.506 0.132 -0.020  0.155
table_std        0.163    0.044  3.667 0.000  0.076  0.250
trade_std        0.024    0.052  0.464 0.643 -0.077  0.125
tree_std         0.308    0.066  4.646 0.000  0.178  0.438
truck_std        0.023    0.054  0.430 0.667 -0.082  0.129
van_std         -0.006    0.046 -0.140 0.888 -0.097  0.084
wall_std        -0.144    0.096 -1.503 0.133 -0.332  0.044
water_std       -0.109    0.055 -2.005 0.045 -0.216 -0.002
windowpane_std  -0.142    0.044 -3.184 0.001 -0.229 -0.054
Group Var        0.668    0.115
==========================================================

In [ ]:
#### GRAFICAR LOS RESULTADOS

In [ ]:
#df = pd.read_csv("mixed_effects_results.csv")

In [ ]:
df.columns

In [19]:
from mixed_table_generator import generate_tables

In [20]:
generate_tables(result, mode="normal")

PDFs generados correctamente ✅🔥

In [13]:
generate_tables(result, mode="filter")

PDFs generados correctamente ✅🔥

In [ ]:
#####################
#   CREAR DATASET   #
#####################

In [ ]:
import pandas as pd
import json

# Cargar el JSON
with open("data_hololens.json", "r") as f:
    data = json.load(f)

# Construir las filas del DataFrame
rows = []
for key in range(150):
    entry = data[str(key)]
    scores = [p["score"] for p in entry["score_participant"]]
    score_mean = sum(scores) / len(scores)
    for p in entry["score_participant"]:
        rows.append({
            "id1": entry["ID"],
            "id2": key,
            "participante": p["participant"],
            "score": p["score"],
            "score_mean": score_mean
        })

df = pd.DataFrame(rows)

In [ ]:
df.head(20)

In [ ]:
df.to_csv("data_hololens.csv", index=False)

In [21]:
import pandas as pd

df = pd.read_csv("df_final1.csv")

In [22]:
df.isnull().sum()

Unnamed: 0       0
Time             0
ImageIndex       0
ImageName        0
X                0
Y                0
Z                0
participante     0
pixelX           0
pixelY           0
class_id        13
class_name      13
ratio           13
hex_color       13
main_class      13
dtype: int64

In [23]:
df.head()

,Unnamed: 0,Time,ImageIndex,ImageName,X,Y,Z,participante,pixelX,pixelY,class_id,class_name,ratio,hex_color,main_class
0,0,7.984,0,3,0.0052,1.0046,1.9762,1,405.2,204.6,7.0,road;route,29.615,#8C8C8C,road
1,1,8.017,0,3,0.0052,1.0060,1.9764,1,405.2,206.0,7.0,road;route,29.615,#8C8C8C,road
2,2,8.052,0,3,0.0053,1.0070,1.9766,1,405.3,207.0,7.0,road;route,29.615,#8C8C8C,road
3,3,8.084,0,3,0.0054,1.0070,1.9768,1,405.4,207.0,7.0,road;route,29.615,#8C8C8C,road
4,4,8.117,0,3,0.0056,1.0059,1.9766,1,405.6,205.9,7.0,road;route,29.615,#8C8C8C,road

In [33]:
pre1 = pd.read_csv("precalculated_fixations1.csv")

In [34]:
pre1.head()

,participante,ImageName,ImageIndex,start_time,end_time,duration,x_centroid,y_centroid,point_count,patch_10_x,...,patch_20_x,patch_20_y,patch_20_index,patch_40_x,patch_40_y,patch_40_index,algorithm,velocity_threshold,min_duration,raw_gaze_points
0,1,3,3,7.984,7.984,0.0,405.2,204.6,1,40,...,20,10,420,10,5,110,I-VT,1.15,0.0,414
1,1,3,3,9.717,9.717,0.0,375.8,198.6,1,37,...,18,9,378,9,4,89,I-VT,1.15,0.0,414
2,1,3,3,9.983,9.983,0.0,399.0,207.3,1,39,...,19,10,419,9,5,109,I-VT,1.15,0.0,414
3,1,3,3,10.616,10.616,0.0,177.5,268.4,1,17,...,8,13,528,4,6,124,I-VT,1.15,0.0,414
4,1,3,3,10.983,10.983,0.0,415.8,233.1,1,41,...,20,11,460,10,5,110,I-VT,1.15,0.0,414

In [35]:
pre = pd.read_csv("precalculated_fixations.csv")

In [36]:
pre.head()

,participante,ImageName,ImageIndex,start_time,end_time,duration,x_centroid,y_centroid,point_count,raw_gaze_points
0,1,3,3,7.984,7.984,0.0,405.2,204.6,1,414
1,1,3,3,9.717,9.717,0.0,375.8,198.6,1,414
2,1,3,3,9.983,9.983,0.0,399.0,207.3,1,414
3,1,3,3,10.616,10.616,0.0,177.5,268.4,1,414
4,1,3,3,10.983,10.983,0.0,415.8,233.1,1,414

In [ ]:
# algorithm, velocity_threshold, min_duration - siempre tienen el mismo valor, son constantes